parameters:
    ezpublish.search.legacy.gateway.criterion_handler.common.tag_id.class: Netgen\TagsBundle\Core\Search\Legacy\Content\Common\Gateway\CriterionHandler\TagId
    ezpublish.search.legacy.gateway.criterion_handler.common.tag_keyword.class: Netgen\TagsBundle\Core\Search\Legacy\Content\Common\Gateway\CriterionHandler\TagKeyword
    ezpublish.search.legacy.gateway.criterion_handler.common.tag_subtree.class: Netgen\TagsBundle\Core\Search\Legacy\Content\Common\Gateway\CriterionHandler\TagSubtree

services:
    ezpublish.search.legacy.gateway.criterion_handler.common.tag_id:
        parent: ezpublish.search.legacy.gateway.criterion_handler.base
        class: %ezpublish.search.legacy.gateway.criterion_handler.common.tag_id.class%
        tags:
            - {name: ezpublish.search.legacy.gateway.criterion_handler.content}
            - {name: ezpublish.search.legacy.gateway.criterion_handler.location}

    ezpublish.search.legacy.gateway.criterion_handler.common.tag_keyword:
        parent: ezpublish.search.legacy.gateway.criterion_handler.base
        class: %ezpublish.search.legacy.gateway.criterion_handler.common.tag_keyword.class%
        tags:
            - {name: ezpublish.search.legacy.gateway.criterion_handler.content}
            - {name: ezpublish.search.legacy.gateway.criterion_handler.location}

    ezpublish.search.legacy.gateway.criterion_handler.common.tag_subtree:
        parent: ezpublish.search.legacy.gateway.criterion_handler.base
        class: %ezpublish.search.legacy.gateway.criterion_handler.common.tag_subtree.class%
        tags:
            - {name: ezpublish.search.legacy.gateway.criterion_handler.content}
            - {name: ezpublish.search.legacy.gateway.criterion_handler.location}
