parameters:
    ezpublish.persistence.legacy.search.gateway.criterion_handler.common.tag_id.class: Netgen\TagsBundle\Core\Persistence\Legacy\Content\Search\Common\Gateway\CriterionHandler\Tags\TagId
    ezpublish.persistence.legacy.search.gateway.criterion_handler.common.tag_keyword.class: Netgen\TagsBundle\Core\Persistence\Legacy\Content\Search\Common\Gateway\CriterionHandler\Tags\TagKeyword

services:
    ezpublish.persistence.legacy.search.gateway.criterion_handler.common.tag_id:
        parent: ezpublish.persistence.legacy.search.gateway.criterion_handler.base
        class: %ezpublish.persistence.legacy.search.gateway.criterion_handler.common.tag_id.class%
        tags:
            - {name: ezpublish.persistence.legacy.search.gateway.criterion_handler.content}
            - {name: ezpublish.persistence.legacy.search.gateway.criterion_handler.location}

    ezpublish.persistence.legacy.search.gateway.criterion_handler.common.tag_keyword:
        parent: ezpublish.persistence.legacy.search.gateway.criterion_handler.base
        class: %ezpublish.persistence.legacy.search.gateway.criterion_handler.common.tag_keyword.class%
        tags:
            - {name: ezpublish.persistence.legacy.search.gateway.criterion_handler.content}
            - {name: ezpublish.persistence.legacy.search.gateway.criterion_handler.location}
