parameters:
    ezpublish.fieldType.eztags.class: Netgen\TagsBundle\Core\FieldType\Tags\Type
    ezpublish.fieldType.eztags.externalStorage.class: Netgen\TagsBundle\Core\FieldType\Tags\TagsStorage
    ezpublish.fieldType.indexable.eztags.class: %ezpublish.fieldType.indexable.unindexed.class%

services:
    ezpublish.fieldType.eztags:
        class: %ezpublish.fieldType.eztags.class%
        parent: ezpublish.fieldType
        arguments: [ @ezpublish.api.service.tags ]
        tags:
            - {name: ezpublish.fieldType, alias: eztags}

    ezpublish.fieldType.eztags.externalStorage:
        class: %ezpublish.fieldType.eztags.externalStorage.class%
        tags:
            - {name: ezpublish.fieldType.externalStorageHandler, alias: eztags}

    ezpublish.fieldType.indexable.eztags:
        class: %ezpublish.fieldType.indexable.eztags.class%
        tags:
            - {name: ezpublish.fieldType.indexable, alias: eztags}
