parameters:
    ezpublish.fieldType.eztags.class: Netgen\TagsBundle\Core\FieldType\Tags\Type
    ezpublish.fieldType.eztags.externalStorage.class: Netgen\TagsBundle\Core\FieldType\Tags\TagsStorage

services:
    ezpublish.fieldType.eztags:
        class: %ezpublish.fieldType.eztags.class%
        parent: ezpublish.fieldType
        tags:
            - {name: ezpublish.fieldType, alias: eztags}

    ezpublish.fieldType.eztags.externalStorage:
        class: %ezpublish.fieldType.eztags.externalStorage.class%
        tags:
            - {name: ezpublish.fieldType.externalStorageHandler, alias: eztags}
