eztags_tag_view_id:
    path: /tags/view/{tagId}
    defaults:
        _controller: eztags.controller.tag_view:viewTagById
    methods: [GET]
    requirements:
        tagId: \d+

eztags_tag_view_url:
    path: /tags/view/{tagUrl}
    defaults:
        _controller: eztags.controller.tag_view:viewTagByUrl
    methods: [GET]
    requirements:
        tagUrl: .+
