dist: xenial

language: php

php:
  - 7.3
  - 7.4snapshot

cache:
  directories:
    - $HOME/.cache/composer

env:
  - CONFIG="phpunit.xml" COVERAGE="unit"
  - CONFIG="phpunit-integration-legacy.xml" COVERAGE="integration"

matrix:
  include:
    - php: 7.3
      env: RUN_PHPSTAN="yes"
    -
      env: ~
      php: ~
      cache: ~
      language: node_js
      node_js: node
      install: yarn install
      before_script: yarn global add grunt-cli
      script:
        - grunt build
  allow_failures:
    - php: 7.4snapshot
  fast_finish: true

branches:
  only:
    - dev
    - master
    - /^\d.\d+-release$/

before_script:
  - echo "memory_limit=-1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini

  # Read-only OAuth token to work around GitHub API rate limits
  - composer config -g github-oauth.github.com "4b3b0a83ea27d9544d3608a384c7a14625a98804"

  - composer update --no-suggest --prefer-dist

script:
  # - composer validate --strict
  - if [ "$CONFIG" != "" ] ; then vendor/bin/phpunit -c $CONFIG --coverage-clover=coverage.xml --colors=always ; fi
  - if [ "$RUN_PHPSTAN" != "" ] ; then composer phpstan ; fi
  - if [ "$RUN_PHPSTAN" != "" ] ; then composer phpstan-tests ; fi

notifications:
  email: false

git:
  depth: 1

# send coverage to codecov.io
after_success:
  - if [ "$COVERAGE" != "" ] ; then bash <(curl -s https://codecov.io/bash) -F $COVERAGE ; fi
