netgen_tags_admin_tag_show:
    path: /show/{tagId}
    controller: eztags.admin.controller.tag:showTagAction
    methods: [GET]

netgen_tags_admin_tag_related_content:
    path: /{tagId}/content
    controller: eztags.admin.controller.related_content:relatedContentAction
    methods: [GET]

netgen_tags_admin_tag_add_select:
    path: /add/{parentId}
    controller: eztags.admin.controller.tag:addTagSelectAction
    methods: [GET, POST]

netgen_tags_admin_tag_add:
    path: /add/{parentId}/{languageCode}
    controller: eztags.admin.controller.tag:addTagAction
    methods: [GET, POST]

netgen_tags_admin_tag_move_tags:
    path: /move/{parentId}
    controller: eztags.admin.controller.tag:moveTagsAction
    methods: [POST]

netgen_tags_admin_tag_copy_tags:
    path: /copy/{parentId}
    controller: eztags.admin.controller.tag:copyTagsAction
    methods: [POST]

netgen_tags_admin_tag_delete_tags:
    path: /delete/{parentId}
    controller: eztags.admin.controller.tag:deleteTagsAction
    methods: [POST]

netgen_tags_admin_tag_update_select:
    path: /{tagId}/update
    controller: eztags.admin.controller.tag:updateTagSelectAction
    methods: [GET, POST]

netgen_tags_admin_tag_update:
    path: /{tagId}/update/{languageCode}
    controller: eztags.admin.controller.tag:updateTagAction
    methods: [GET, POST]

netgen_tags_admin_tag_delete:
    path: /{tagId}/delete
    controller: eztags.admin.controller.tag:deleteTagAction
    methods: [GET, POST]

netgen_tags_admin_tag_merge:
    path: /{tagId}/merge
    controller: eztags.admin.controller.tag:mergeTagAction
    methods: [GET, POST]

netgen_tags_admin_tag_convert:
    path: /{tagId}/convert
    controller: eztags.admin.controller.tag:convertToSynonymAction
    methods: [GET, POST]

netgen_tags_admin_tag_translation:
    path: /{tagId}/translation
    controller: eztags.admin.controller.tag:translationAction
    methods: [POST]

netgen_tags_admin_tag_children:
    path: /{tagId}/children
    controller: eztags.admin.controller.tag:childrenAction
    methods: [POST]
