netgen_tags_admin_tag_show:
    path: /show/{tagId}
    defaults:
        _controller: eztags.admin.controller.tag:showTagAction
        _method: GET

netgen_tags_admin_tag_related_content:
    path: /{tagId}/content
    defaults:
        _controller: eztags.admin.controller.related_content:relatedContentAction
        _method: GET

netgen_tags_admin_tag_add_select:
    path: /add/{parentId}
    defaults:
        _controller: eztags.admin.controller.tag:addTagSelectAction
        _method: [GET, POST]

netgen_tags_admin_tag_add:
    path: /add/{parentId}/{languageCode}
    defaults:
        _controller: eztags.admin.controller.tag:addTagAction
        _method: [GET, POST]

netgen_tags_admin_tag_move_tags:
    path: /move/{parentId}
    defaults:
        _controller: eztags.admin.controller.tag:moveTagsAction
        _method: POST

netgen_tags_admin_tag_copy_tags:
    path: /copy/{parentId}
    defaults:
        _controller: eztags.admin.controller.tag:copyTagsAction
        _method: POST

netgen_tags_admin_tag_delete_tags:
    path: /delete/{parentId}
    defaults:
        _controller: eztags.admin.controller.tag:deleteTagsAction
        _method: POST

netgen_tags_admin_tag_update_select:
    path: /{tagId}/update
    defaults:
        _controller: eztags.admin.controller.tag:updateTagSelectAction
        _method: [GET, POST]

netgen_tags_admin_tag_update:
    path: /{tagId}/update/{languageCode}
    defaults:
        _controller: eztags.admin.controller.tag:updateTagAction
        _method: [GET, POST]

netgen_tags_admin_tag_delete:
    path: /{tagId}/delete
    defaults:
        _controller: eztags.admin.controller.tag:deleteTagAction
        _method: [GET, POST]

netgen_tags_admin_tag_merge:
    path: /{tagId}/merge
    defaults:
        _controller: eztags.admin.controller.tag:mergeTagAction
        _method: [GET, POST]

netgen_tags_admin_tag_convert:
    path: /{tagId}/convert
    defaults:
        _controller: eztags.admin.controller.tag:convertToSynonymAction
        _method: [GET, POST]

netgen_tags_admin_tag_translation:
    path: /{tagId}/translation
    defaults:
        _controller: eztags.admin.controller.tag:translationAction
        _method: POST

netgen_tags_admin_tag_children:
    path: /{tagId}/children
    defaults:
        _controller: eztags.admin.controller.tag:childrenAction
        _method: POST
