system:
    default:
        yui:
            modules:
                netgen-tags-app-plugin:
                    requires: ['ez-pluginregistry', 'plugin', 'base', 'netgen-tags-serverside-view', 'netgen-tags-serverside-view-service']
                    dependencyOf: ['ez-platformuiapp']
                    path: bundles/netgentags/platformui/js/apps/plugins/netgen-tags-app-plugin.js

                netgen-tags-serverside-view:
                    requires: ['ez-serversideview']
                    path: bundles/netgentags/platformui/js/views/netgen-tags-serverside-view.js

                netgen-tags-serverside-view-service:
                    requires: ['ez-serversideviewservice']
                    path: bundles/netgentags/platformui/js/views/services/netgen-tags-serverside-view-service.js

                netgen-tags-content-type-edit-serverside-view-plugin:
                    requires: ['ez-pluginregistry', 'plugin', 'base']
                    dependencyOf: ['ez-contenttypeeditserversideview']
                    path: bundles/netgentags/platformui/js/views/plugins/netgen-tags-content-type-edit-serverside-view-plugin.js

                netgen-tags-navigation-view-plugin:
                    requires: ['ez-pluginregistry', 'plugin', 'base']
                    dependencyOf: ['ez-navigationhubview']
                    path: bundles/netgentags/platformui/js/views/plugins/netgen-tags-navigation-view-plugin.js

                netgen-tags-navigation-view-service-plugin:
                    requires: ['ez-pluginregistry', 'ez-viewservicebaseplugin', 'ez-navigationitemview']
                    dependencyOf: ['ez-navigationhubviewservice']
                    path: bundles/netgentags/platformui/js/views/services/plugins/netgen-tags-navigation-view-service-plugin.js

                netgen-tags-field-view:
                    requires: ['ez-fieldview', 'netgentagsfieldview-ez-template']
                    path: bundles/netgentags/platformui/js/views/field/netgen-tags-field-view.js
                netgentagsfieldview-ez-template:
                    type: template
                    path: bundles/netgentags/platformui/js/views/field/templates/netgen-tags-field-view.hbt
                ez-rawcontentview:
                    requires: ['netgen-tags-field-view']
